image: Visual Studio 2022

configuration: Release

install:
  - ps: |
      nuget restore Selone.sln
      dotnet restore

build:
  project: Selone.sln
  publish_nuget: true
  verbosity: minimal

test: off

deploy:
  - provider: NuGet
    api_key:
      secure: gKLEfhlRtIFnS9joCT9oqAMx3MC7JArdfpfQlEBocObFG4qigbKJpmGMNtvVCtQ7
    skip_symbols: true
    on:
      branch: /^master$/
